### ISSUE TITLE
Licence is missing

### ISSUE THREAD

**Issue by kathir-t** [ColorlibHQ/email-templates#3]
Please add the usage license (like Apache 2.0 license, MIT license, GPL etc...)

**Comment by Dima-ja** [comment]
Hello 

I want to use the news letter code " the winter is coming" and I want to know which license does it have?

thanks

**Comment by andrewshadura** [comment]
@puikinsh, could you please clarify the license?
Thanks!

**Comment by puikinsh** [comment]
They are licensed under the MIT license.
